import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'
const supabase = createClient('https://ywbmlsfxvytdmnkyjial.supabase.co','sb_publishable_Esj-3c_n0bYl0QwHzIp7kg_jGuUS2j9')
const OPEN=8*60,CLOSE=18*60,STEP=30,BUFFER=10
const state={screen:'home',services:[],service:null,date:'',start:null,busy:[],viewMonth:new Date()}
const $=s=>document.querySelector(s)
const els={back:$('#backButton'),home:$('#homeButton'),start:$('#startButton'),newBooking:$('#newBookingButton'),services:$('#servicesList'),servicesStatus:$('#servicesStatus'),prev:$('#prevMonth'),next:$('#nextMonth'),month:$('#monthLabel'),cal:$('#calendarGrid'),times:$('#timesGrid'),timesStatus:$('#timesStatus'),continue:$('#continueButton'),form:$('#bookingForm'),name:$('#nameInput'),phone:$('#phoneInput'),book:$('#bookButton'),formStatus:$('#formStatus'),sumService:$('#summaryService'),sumDate:$('#summaryDate'),sumTime:$('#summaryTime'),sumArt:$('#summaryArt'),successText:$('#successText')}
function show(name){state.screen=name;document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));els.back.classList.toggle('hidden',name==='home'||name==='success');els.home.classList.toggle('hidden',name==='home');window.scrollTo({top:0,behavior:'smooth'})}
function back(){if(state.screen==='services')show('home');else if(state.screen==='datetime')show('services');else if(state.screen==='confirm')show('datetime')}
function pad(n){return String(n).padStart(2,'0')}function dbMin(t){const [h,m]=t.split(':').map(Number);return h*60+m}function dbTime(m){return `${pad(Math.floor(m/60))}:${pad(m%60)}:00`}function timeLabel(m){const h=Math.floor(m/60),mm=m%60,p=h>=12?'p. m.':'a. m.';return `${h%12||12}:${pad(mm)} ${p}`}function iso(y,m,d){return `${y}-${pad(m+1)}-${pad(d)}`}function fmtDate(v){const [y,m,d]=v.split('-').map(Number);return new Intl.DateTimeFormat('es-CO',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(y,m-1,d))}function overlap(a1,a2,b1,b2){return a1<b2&&a2>b1}
function art(name=''){const n=name.toLowerCase();if(n.includes('pedicure'))return'pedicure';if(n.includes('acrí')||n.includes('acri'))return'acrylic';if(n.includes('polygel'))return'polygel';if(n.includes('dipping'))return'dipping';if(n.includes('press'))return'press';if(n.includes('retiro'))return'removal';return''}
async function loadServices(){els.servicesStatus.textContent='Cargando servicios...';const {data,error}=await supabase.from('Servicios').select('id,nombre,duracion_minutos').eq('activo',true).order('id');if(error){console.error(error);els.servicesStatus.className='status error';els.servicesStatus.textContent='No pudimos cargar los servicios.';return}state.services=data||[];renderServices();els.servicesStatus.textContent=''}
function renderServices(){els.services.innerHTML='';state.services.forEach(s=>{const b=document.createElement('button');b.type='button';b.className=`service-card ${art(s.nombre)}`;b.innerHTML=`<span class="service-art"></span><span><strong>${escapeHtml(s.nombre)}</strong><small>Seleccionar</small></span><span class="arrow">›</span>`;b.onclick=()=>{state.service=s;state.date='';state.start=null;state.viewMonth=new Date();renderCalendar();els.times.innerHTML='';els.timesStatus.textContent='Elige primero una fecha.';els.continue.disabled=true;show('datetime')};els.services.appendChild(b)})}
function todayStart(){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function isUnavailable(y,m,d){const date=new Date(y,m,d),today=todayStart();return date<today||date.getDay()===0}
function renderCalendar(){const vm=state.viewMonth,y=vm.getFullYear(),m=vm.getMonth();els.month.textContent=new Intl.DateTimeFormat('es-CO',{month:'long',year:'numeric'}).format(new Date(y,m,1));els.cal.innerHTML='';const first=new Date(y,m,1).getDay();const offset=(first+6)%7;for(let i=0;i<offset;i++){const s=document.createElement('span');s.className='day blank';els.cal.appendChild(s)}const days=new Date(y,m+1,0).getDate();for(let d=1;d<=days;d++){const b=document.createElement('button');b.type='button';b.className='day';b.textContent=d;const value=iso(y,m,d),disabled=isUnavailable(y,m,d);if(disabled){b.disabled=true;b.classList.add('disabled')}if(value===state.date)b.classList.add('selected');b.onclick=()=>selectDate(value);els.cal.appendChild(b)}const now=todayStart();const thisMonth=new Date(now.getFullYear(),now.getMonth(),1);els.prev.disabled=new Date(y,m,1)<=thisMonth}
async function selectDate(value){state.date=value;state.start=null;renderCalendar();await refreshTimes()}
async function busy(date){const {data,error}=await supabase.rpc('horarios_ocupados',{p_fecha:date});if(error)throw error;return(data||[]).map(r=>({start:dbMin(r.hora_inicio),end:dbMin(r.hora_fin)}))}
async function refreshTimes(){els.times.innerHTML='';els.continue.disabled=true;if(!state.service||!state.date)return;els.timesStatus.textContent='Consultando disponibilidad...';try{state.busy=await busy(state.date)}catch(e){console.error(e);els.timesStatus.className='status error';els.timesStatus.textContent='No pudimos consultar la agenda.';return}const duration=Number(state.service.duracion_minutos),available=[];for(let s=OPEN;s+duration<=CLOSE;s+=STEP){const end=s+duration;if(!state.busy.some(r=>overlap(s,end+BUFFER,r.start,r.end)))available.push(s)}if(!available.length){els.timesStatus.textContent='No hay horarios disponibles para ese día.';return}available.forEach(s=>{const b=document.createElement('button');b.type='button';b.className='time-btn';b.textContent=timeLabel(s);b.onclick=()=>{document.querySelectorAll('.time-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.start=s;els.continue.disabled=false};els.times.appendChild(b)});els.timesStatus.className='status';els.timesStatus.textContent='Selecciona la hora que prefieras.'}
function updateSummary(){els.sumService.textContent=state.service.nombre;els.sumDate.textContent=fmtDate(state.date);els.sumTime.textContent=timeLabel(state.start);els.sumArt.className=`service-art ${art(state.service.nombre)}`}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function makeId(){return Date.now()*1000+Math.floor(Math.random()*1000)}
els.start.onclick=()=>show('services');els.home.onclick=()=>show('home');els.back.onclick=back;els.prev.onclick=()=>{state.viewMonth=new Date(state.viewMonth.getFullYear(),state.viewMonth.getMonth()-1,1);renderCalendar()};els.next.onclick=()=>{state.viewMonth=new Date(state.viewMonth.getFullYear(),state.viewMonth.getMonth()+1,1);renderCalendar()};els.continue.onclick=()=>{if(state.service&&state.date&&state.start!==null){updateSummary();show('confirm')}};els.newBooking.onclick=()=>{state.service=null;state.date='';state.start=null;els.name.value='';els.phone.value='';els.formStatus.textContent='';show('home')}
els.form.onsubmit=async e=>{e.preventDefault();els.formStatus.className='status';els.formStatus.textContent='';const nombre=els.name.value.trim(),whatsapp=els.phone.value.trim();if(!nombre||!whatsapp){els.formStatus.className='status error';els.formStatus.textContent='Completa tu nombre y WhatsApp.';return}els.book.disabled=true;els.book.textContent='Agendando...';try{const current=await busy(state.date),end=state.start+Number(state.service.duracion_minutos);if(current.some(r=>overlap(state.start,end+BUFFER,r.start,r.end))){els.formStatus.className='status error';els.formStatus.textContent='Ese horario acaba de ocuparse. Elige otro.';await refreshTimes();show('datetime');return}const {error}=await supabase.from('Citas').insert({id:makeId(),nombre_cliente:nombre,whatsapp,servicio_id:state.service.id,fecha:state.date,hora_inicio:dbTime(state.start),hora_fin:dbTime(end),estado:'confirmada'});if(error)throw error;els.successText.textContent=`${state.service.nombre} · ${fmtDate(state.date)} · ${timeLabel(state.start)}.`;show('success')}catch(err){console.error(err);els.formStatus.className='status error';els.formStatus.textContent='No pudimos guardar la cita. Intenta nuevamente.'}finally{els.book.disabled=false;els.book.textContent='Agendar cita'}}
renderCalendar();loadServices()
